from typing import Optional

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    message: str = Field(
        ...,
        min_length=1,
        description="User prompt or message for Atles",
    )

    conversation_id: Optional[int] = Field(
        default=None,
        description=(
            "Existing conversation ID. "
            "If omitted, Atles creates a new conversation."
        ),
    )


class ChatResponse(BaseModel):
    response: str = Field(
        ...,
        description="Response generated by Atles",
    )

    conversation_id: int = Field(
        ...,
        description="Conversation ID used for this message",
    )